
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
   broker: !secret qmttserver
   discovery: true
   discovery_prefix: ha
   username: !secret mqttusername
   password: !secret mqttpassword

shell_command:
   scriptstartup: /config/scripts/startupscript.sh

binary_sensor:
  - platform: mqtt
    name: Furnace
    state_topic: "/home/furnace/state/#"
    payload_on: "on"
    payload_off: "off"

notify:
   - name: notify_sms
     platform: smtp
     sender: !secret senderemail
     recipient: !secret cellsmsgateway
     server: smtp.gmail.com
     username: !secret emailusername
     password: !secret emailpassword
